# Generated by Django 3.1.12 on 2021-06-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teams',
            field=models.ManyToManyField(blank=True, to='team.Team', verbose_name='Команды профиля'),
        ),
    ]
