# Generated by Django 3.1.12 on 2021-06-07 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='profile_images/', verbose_name='Фото профиля')),
                ('position', models.CharField(max_length=256, verbose_name='Должность профиля')),
                ('majors', models.ManyToManyField(related_name='major', to='account.Profile', verbose_name='Начальники профиля')),
                ('minors', models.ManyToManyField(related_name='minor', to='account.Profile', verbose_name='Подчиненные профиля')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team', verbose_name='Команда профиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь профиля')),
            ],
        ),
    ]
