# Generated by Django 3.1.12 on 2021-06-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='team',
        ),
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.ManyToManyField(to='team.Team', verbose_name='Команды профиля'),
        ),
    ]
