# Generated by Django 3.1.12 on 2021-06-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210608_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='team',
            new_name='teams',
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=256, verbose_name='Должность профиля'),
        ),
    ]
