# Generated by Django 3.1.12 on 2021-06-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('account', '0003_auto_20210608_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='majors',
            field=models.ManyToManyField(blank=True, related_name='major', to='account.Profile', verbose_name='Начальники профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='minors',
            field=models.ManyToManyField(blank=True, related_name='minor', to='account.Profile', verbose_name='Подчиненные профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='teams',
            field=models.ManyToManyField(blank=True, to='team.Team', verbose_name='Команды профиля'),
        ),
    ]
