# Generated by Django 3.1.12 on 2021-06-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210608_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='majors',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='minors',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
    ]
