# Generated by Django 3.1.12 on 2021-06-20 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название доски')),
                ('priority', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('color', models.CharField(max_length=256, verbose_name='Цвет задачи')),
                ('deadline', models.DateTimeField(verbose_name='Время выполнения')),
                ('priority', models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True)),
                ('difficulty', models.CharField(choices=[(50, 'easy'), (100, 'medium'), (200, 'hard')], max_length=128, verbose_name='Сложность задачи')),
                ('is_completed', models.BooleanField(verbose_name='Выполнена ли задача')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='board.board', verbose_name='Доска задачи')),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.contributor', verbose_name='Исполнитель задачи')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.task', verbose_name='Подзадача')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.contributor')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.task')),
            ],
        ),
    ]
