# Generated by Django 3.1.12 on 2021-06-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
