# Generated by Django 3.1.12 on 2021-06-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20210622_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='when_completed',
            field=models.DateTimeField(null=True, verbose_name='Когда задача завершена'),
        ),
    ]
