# Generated by Django 3.1.12 on 2021-06-20 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название должности')),
                ('position', models.CharField(choices=[(1, 'creator'), (2, 'admin'), (3, 'project_manager'), (4, 'middle_contributor'), (5, 'junior_contributor')], max_length=128, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название команды')),
                ('avatar', models.ImageField(default='team_avatars/no_img.png', null=True, upload_to='team_avatars')),
                ('description', models.TextField(verbose_name='Описание команды')),
                ('is_self', models.BooleanField(verbose_name='Единичная псевдокоманда для привязки Board к профилю')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team', verbose_name='Подкоманда')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.position', verbose_name='Должность')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник команды')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team', verbose_name='Команда участника')),
            ],
        ),
    ]
