# Generated by Django 3.1.12 on 2021-06-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='team.team', verbose_name='Команда участника'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_self',
            field=models.BooleanField(default=False, verbose_name='Единичная псевдокоманда для привязки Board к профилю'),
        ),
        migrations.AlterField(
            model_name='team',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_teams', to='team.team', verbose_name='Подкоманда'),
        ),
    ]
