# Generated by Django 3.1.12 on 2021-06-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='count_of_contributors',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество участников команды'),
        ),
    ]
