# Generated by Django 3.1.12 on 2021-06-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_count_of_contributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='count_of_contributors',
        ),
    ]
