# Generated by Django 3.1.12 on 2021-06-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20210608_2215'),
        ('team', '0004_remove_team_count_of_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='children', to='account.Profile', verbose_name='Список участников команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='account.profile', verbose_name='Создатель команды'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название проекта')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.profile', verbose_name='Создатель проекта')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
